"""Compatibility module for launching the Claude Bridge MCP server via python -m."""

from claude_bridge.server import (
    build_context_pack,
    configure_from_env,
    find_relevant_files,
    get_config,
    get_recent_tool_calls,
    index_codebase,
    interact_with_process,
    kill_process,
    list_directory,
    list_process_sessions,
    mcp,
    patch_file,
    preview_patch,
    read_file,
    read_multiple_files,
    read_process_output,
    run_agent_loop_session,
    run_agent_loop_step,
    run_mcp_server,
    run_shell,
    search_in_files,
    set_config,
    set_config_value,
    suggest_validation_commands,
    switch_project_root,
    start_process,
    undo_last_patch,
    write_file,
    workspace_status,
)

__all__ = [
    "mcp",
    "set_config",
    "configure_from_env",
    "build_context_pack",
    "get_config",
    "read_file",
    "read_multiple_files",
    "list_directory",
    "write_file",
    "search_in_files",
    "run_shell",
    "start_process",
    "read_process_output",
    "interact_with_process",
    "list_process_sessions",
    "kill_process",
    "suggest_validation_commands",
    "patch_file",
    "preview_patch",
    "undo_last_patch",
    "run_agent_loop_session",
    "run_agent_loop_step",
    "index_codebase",
    "find_relevant_files",
    "get_recent_tool_calls",
    "set_config_value",
    "workspace_status",
    "switch_project_root",
    "run_mcp_server",
]


if __name__ == "__main__":
    configure_from_env()
    run_mcp_server()
