apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nulm-hpa
  labels:
    app: nulm
    app.kubernetes.io/name: nulm
    app.kubernetes.io/component: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nulm
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70