apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "nulm.fullname" . }}-pdb
  labels:
    app: nulm
    app.kubernetes.io/name: {{ include "nulm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: core
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: nulm