apiVersion: v1
kind: Service
metadata:
  name: {{ include "nulm.fullname" . }}
  labels:
    app: nulm
    app.kubernetes.io/name: {{ include "nulm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: core
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nulm
  ports:
    - name: dashboard
      port: {{ .Values.service.ports.dashboard }}
      targetPort: {{ .Values.service.ports.dashboard }}
      protocol: TCP
    - name: health
      port: {{ .Values.service.ports.health }}
      targetPort: {{ .Values.service.ports.health }}
      protocol: TCP